name: lint
run-name: ${{ github.actor }} pushes changes to the ${{ github.ref_name }}
on:
  push:
    branches:
      - "main"
jobs:
  lint-and-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"
      - name: install dependencies
        run: npm ci
      - name: runing ts
        run: npm run ts
      - name: runing lint
        run: npm run lint
